# Generated by Django 4.1.6 on 2023-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_historicalproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicator',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmeasureunit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='measure_unit',
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicador de Oferta', 'verbose_name_plural': 'Indicadores de Ofertas'},
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='HistoricalCategoryProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicator',
        ),
        migrations.DeleteModel(
            name='HistoricalMeasureUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
